### ISSUE TITLE
不好意思，想请教个自定义卡面上传图片，cdn

### ISSUE THREAD

**Issue by keryhu** [zxyqwe/tp5app#1]
-设置基础卡面背景图片
开发者可以为会员卡设置一套自定义卡面，在调用创建会员卡接口时，传入backgroud_pic_url字段可以定义自定义卡面，注意，开发者须先将设计好的会员卡卡面上传至腾讯CDN，并获取url作为backgroud_pic_url。

这里如何上传 图片到 腾讯cdn，找半天没找到例子。在哪里上传。有没有相关文档

**Comment by zxyqwe** [comment]
我个人使用的是[微信公众平台技术文档]->[素材管理]->[新增永久素材]->[上传图文消息内的图片获取URL]
接口在 https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=ACCESS_TOKEN
返回的URL在http://mmbiz.qpic.cn 域名下

**Comment by keryhu** [comment]
哦哦，
谢谢！
我最近也在做小程序方面开发，
有空可以多交流。我的微信号：15900455491

在 2019年1月23日，下午10:33，zxyqwe <notifications@github.com<mailto:notifications@github.com>> 写道：


我个人使用的是[微信公众平台技术文档]->[素材管理]->[新增永久素材]->[上传图文消息内的图片获取URL]
接口在 https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=ACCESS_TOKEN
返回的URL在http://mmbiz.qpic.cn域名下<http://mmbiz.qpic.xn--cn-uv2cp0vy9e/>

**Comment by edwincen** [comment]
> 我个人使用的是[微信公众平台技术文档]->[素材管理]->[新增永久素材]->[上传图文消息内的图片获取URL]
> 接口在 https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=ACCESS_TOKEN
> 返回的URL在http://mmbiz.qpic.cn 域名下

你好，请问这个接口是有每天调用限制的，1000-到5000不能，但都会超过，请问怎么解决，能不能上传到哪怕是腾讯云的CDN上

**Comment by zxyqwe** [comment]
> > 我个人使用的是[微信公众平台技术文档]->[素材管理]->[新增永久素材]->[上传图文消息内的图片获取URL]
> > 接口在 https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=ACCESS_TOKEN
> > 返回的URL在http://mmbiz.qpic.cn 域名下
> 
> 你好，请问这个接口是有每天调用限制的，1000-到5000不能，但都会超过，请问怎么解决，能不能上传到哪怕是腾讯云的CDN上

抱歉，我没有用过这么大量，也就是一天几次上传而已。
